version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: "Hello!"
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: "Hello!"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
